services:
  go:
    image: seicheese:go
    container_name: go
    ports:
      - "1300:1300"
      - "443:443"
    volumes:
      - ./src:/home/user/go/src/app
      - ./ssl:/home/user/go/src/app/ssl
      - letsencrypt:/etc/letsencrypt
    tty: true
    # command: air -c .air.toml
    env_file:
      - .env
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 20.0.0.2

  db:
    image: seicheese:db
    container_name: seicheese-db
    ports:
      - "3312:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      net:
        ipv4_address: 20.0.0.3

  pma:
    image: seicheese:admin
    container_name: seicheese-admin
    ports:
      - "8880:80"
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 20.0.0.4

  certbot:
    image: certbot/certbot
    container_name: seicheese-certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./ssl:/ssl
    network_mode: host
    command: certonly --standalone -d api.seicheese.jp --agree-tos --email your@email.com --preferred-challenges http
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      net:
        ipv4_address: 20.0.0.6

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/24
          gateway: 20.0.0.1
        

volumes:
  db-data:
    driver: local
  letsencrypt:
    driver: local
