# Go
FROM golang:1.22.5 AS go-base

# Port to expose
EXPOSE 1300

# Create User
ARG USERNAME=user
ARG GROUPNAME=user
ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID $GROUPNAME && useradd -m -s /bin/bash  -u $UID -g $GID $USERNAME

# Set Home Environment
ENV HOME /home/${USERNAME}

# Change User
USER $USERNAME

# Set GOPATH
ENV GOPATH ${HOME}/go


# Go-dev
FROM go-base AS go-dev

# Workdir
WORKDIR /home/user/go/src/app

# Set permissons
RUN chown -R $USERNAME:$GROUPNAME /home/user/go

# # Copy to go.mod and go.sum
COPY --chown=user:user ./go/go.mod ./go/go.sum ./

# # Install dependencies
RUN go mod download

# Air Install
RUN go install github.com/air-verse/air@latest

# PATH
ENV PATH $PATH:${GOPATH}/bin



# Database
FROM mysql:8.4.0 AS db-base

# Port to expose
EXPOSE 3306

# Copy to my.cnf
COPY ./mysql/my.cnf /etc/mysql/my.cnf

# Set Common Environments
ENV TZ=Asia/Tokyo
ENV MYSQL_DATABASE=seicheese


# Database-dev
FROM db-base AS db-dev

# Set Development Environments
ENV MYSQL_ROOT_PASSWORD=Wario-51



# Phpmyadmin
FROM phpmyadmin:5.2.1 AS admin

# Port to expose
EXPOSE 80

# Set Environments
ENV PMA_HOST=db
ENV PMA_USER=root
ENV PMA_PASSWORD=Wario-51