// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CheckinLogs    string
	Contents       string
	Genres         string
	GooseDBVersion string
	Places         string
	PointLogs      string
	Points         string
	Seichies       string
	Users          string
}{
	CheckinLogs:    "checkin_logs",
	Contents:       "contents",
	Genres:         "genres",
	GooseDBVersion: "goose_db_version",
	Places:         "places",
	PointLogs:      "point_logs",
	Points:         "points",
	Seichies:       "seichies",
	Users:          "users",
}
